### ISSUE TITLE
Treinar modelo para classificar as propostas

### ISSUE THREAD

**Issue by chaydson** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#1]
Constatamos que o cliente quer um modelo de predição. Um modelo para classificar as propostas do Brasil Participativo nas categorias (baseadas nos ministérios) já listadas no site.

Pegaremos as propostas através de um [bot](https://t.me/decidim_bot) do Telegram ou de uma [planilha](https://docs.google.com/spreadsheets/d/1oK9khP41wYIGxa0yxdbRH0EfhjG26W6_/edit#gid=1471938581), que atualmente é utualizado manualmente. Até então, o Spacy parece atender as nossas demandas.

**Comment by LexTOliver** [comment]
Links úteis:
- [Treinando um classificador de categorias](https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html#training-a-classifier)
- [Machine Learning - Text Processing](https://towardsdatascience.com/machine-learning-text-processing-1d5a2d638958) (a partir da etapa 3)

Obs.: Os dois links apresentam tutoriais completos para trabalhar com dados textuais em ML (a extração, pré-processamento e treinamento de modelo). Para esta issue, apenas o tópico de treinamento possa interessar.
