### ISSUE TITLE
Pré-processamento dos dados

### ISSUE THREAD

**Issue by chaydson** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#11]
Realizar pré-processamento dos dados presentes na planilha
Fazer até 10/07/2023

**Comment by LexTOliver** [comment]
Links úteis:
- [Machine Learning - Text Processing](https://towardsdatascience.com/machine-learning-text-processing-1d5a2d638958)
- [Working with Text Data - Scikit Learn](https://towardsdatascience.com/machine-learning-text-processing-1d5a2d638958)
- [Working With Text Data In Machine Learning](https://medium.com/hamoye-blogs/working-with-text-data-in-machine-learning-30702416706)

Obs.: Alguns links apresentam o tutorial completo para trabalhar com processamento de texto. A parte que concerne à esta issue seria a parte de pré-processamento do texto e representação do texto em vetor.

**Comment by LexTOliver** [comment]
- [Planilha limpa de Propostas](https://docs.google.com/spreadsheets/d/18QFOl_8mzdhOyVJK6YObGbqEpv6OkXFJ/edit#gid=1547191736): Podemos partir dessa planilha para pré-processamento das propostas.

**Comment by chaydson** [comment]
Links para estudo:

https://www.youtube.com/watch?v=ibi5hvw6f3g
https://spacy.io/api/textcategorizer
https://scikit-learn.org/stable/auto_examples/index.html#classification
