### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by chaydson** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#16]
Issue destinada a avaliação da performance de diferentes modelos em um dataset parecido

**Comment by LexTOliver** [comment]
O dataset utilizado para benchmark é o [News Category Dataset](https://www.kaggle.com/datasets/rmisra/news-category-dataset), disponível no Kaggle.

**Comment by chaydson** [comment]
Modelo usado para criar uma classificador usando redes neurais.
