### ISSUE TITLE
Criação do script de download dos dados

### ISSUE THREAD

**Issue by chaydson** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#18]
Resolução do bug que ocorre ao fazer o dowloado do arquivo zip disponível na plataforma do Brasil Participativo.

**Comment by LexTOliver** [comment]
Ao realizar um requisição no link "https://brasilparticipativo.presidencia.gov.br/open-data/download" (link disponível no rodapé do site do Brasil Participativo), utilizando a biblioteca Requests, com o comando get, o seguinte erro é retornado:

![Screenshot from 2023-08-03 11-52-15](https://github.com/ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural/assets/27731119/b45a75ab-5296-488e-848b-f92f4e4ef793)

**Comment by LexTOliver** [comment]
O diagnóstico, vide [StackOverflow](https://stackoverflow.com/questions/71006708/getting-sslv3-alert-handshake-failure-when-trying-to-connect-to-imap) é o seguinte: nas versões mais recentes do Python (3.10.x), foi aprimorada as configurações padrões de segurança da pilha TLS proibindo cifras que ainda utilizam a troca de chave RSA. Os certificados digitais do Brasil Participativo (ou da Autoridade Certificadora) ainda utilizam o padrão antigo de criptografia. Logo, ao realizar a requisição no Python, o acesso é bloqueado causando o erro acima.

Solução: Retroceder a versão do pacote **urllib3** (pacote interno do Python para requisições HTTP) para a **versão 1.26.5**. Essa versão permite a requisição com os certificados digitais antigos e não causa conflito de depedência nos demais pacotes utilizados no projeto. Essa é uma solução temporária até que os certificados digitais do Brasil Participativo sejam atualizados.
