### ISSUE TITLE
Criar um script para buscar os dados automaticamente

### ISSUE THREAD

**Issue by chaydson** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#2]
criar um script para buscar os dados automaticamente
Fazer até 10/07/2023

**Comment by LexTOliver** [comment]
Seria interessante desenvolver um script todo em pyhton, ou talvez uma parte em shell e depois passar para python.

**Comment by LexTOliver** [comment]
O processo do script seria o seguinte:
- Baixar arquivo zip através do link de [Dados Abertos](https://brasilparticipativo.presidencia.gov.br/open-data/download)
- Extrair arquivo csv com os dados
- Extrair e pré-processar os dados da lista:
 - Lista de categorias
 - Lista de propostas (título e corpo)
- (Seria interessante) exportar dados processados para outro arquivo csv
