### ISSUE TITLE
Estudar/Pesquisar modelos few-shot

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#29]
# Descrição
Estudar e pesquisar modelos _few-shot_ (modelos treinados com poucos dados) para conseguir uma acurácia maior no modelo de classificação de propostas (SLClassifier), dada a pouca quantidade de propostas para determinadas categorias.

# Tarefas
- [x] Ler artigos sobre modelos _few-shot_ para classificação de texto.
- [x] Buscar tutoriais com implementação de modelos _few-shot_.

# Critérios de Aceitação
- [ ] Branch com as alterações pedidas aprovada pelo grupo

**Comment by LexTOliver** [comment]
O [PapersWithCode](https://paperswithcode.com/task/few-shot-text-classification) possui uma categoria listando modelos _few-shot_ para classificação de texto.

**Comment by LexTOliver** [comment]
Muitos artigos salientam o uso de modelos [Embeddings](https://huggingface.co/blog/getting-started-with-embeddings) (baseado principalmente em BERT) para representação vetorial do texto juntamente com o cálculo de [similaridade por cosseno](https://youtu.be/e9U0QAFbfLI?si=V4CIs8uXoRl6ruXt) para lidar com Text Classification com poucos dados.

**Comment by LexTOliver** [comment]
Segundo [pesquisas](https://youtu.be/QWzVD0O0O9w?si=KAqi30f-zG8cxz0e), NLP teve um grande salto tecnológico com a introdução dos modelos baseados em Transformers (como o BERT), mas a adoção por parte da indústria ainda é baixo devido a falta de dados com quaildade. Isso tem movido as pesquisas mais recentes da área para criar modelos few-shot learning, e quem sabe modelos zero-shot learning. Até então, o HuggingFace já apresenta 179 modelos para zero-shot classification.

Isso evidencia, o caráter emergente de algoritmos e modelos few-shot para classificação textual.

**Comment by LexTOliver** [comment]
Seleção de alguns artigos:
- [Few-Shot Text Classification - Cloudera](https://few-shot-text-classification.fastforwardlabs.com/)

**Comment by LexTOliver** [comment]
Sentence-BERT (SBERT) addresses these issues. First [published](https://arxiv.org/abs/1908.10084) in 2019, this version of BERT is specifically designed for tasks like semantic similarity search and clustering. PARA CLASSIFICAÇÃO EM TÓPICOS.

**Comment by LexTOliver** [comment]
Foram separados alguns artigos para estudo e teste (comentário acima). Esses serão utilizados durante o próximo sprint para avaliar a usabilidade e aplicabilidade no projeto.
