### ISSUE TITLE
Otimização de dados e do pré-processamento do SLClassifier

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#30]
# Descrição
Testar diferentes algoritmos e técnicas de pré-processamento, manipulação dos dados para conseguir uma acurácia maior no modelo de classificação de propostas.

# Tarefas
- [x] Aumentar a atual acurácia geral do modelo.

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovada pelo grupo ou registro na issue com as atividades realizadas.

**Comment by jpanacleto2** [comment]
Foram testados diversos algoritmos e tecnicas de pre processamento disponibilzados na pasta de versionamento de modelos dentro da pasta production.
