### ISSUE TITLE
Integração do algoritmo ML no Ruby

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#32]
# Descrição
Buscar formas de integração do SLClassifier (em Python) no Ruby. Além disso, avaliar a necessidade, dificuldade, vantagens e desvantagens de implementar o algoritmo ML em Ruby caso não seja possível carregar o modelo em Python no Ruby.

# Tarefas
- [x] Avaliar se as técnicas se adequam aos protocolos do cliente e do Brasil Participativo.

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovada pelo grupo.

**Comment by LexTOliver** [comment]
[Persistência do modelo - Formatos interoperáveis](https://scikit-learn.org/stable/model_persistence.html#interoperable-formats): esse tópico da biblioteca Scikit-Learn apresenta algumas formas de salvar o modelo treinado em um formato que seja interoperável entre linguagens. Pode ser interessante para avaliar como vamos guardar o modelo para ser integrado ao Ruby, linguagem na qual o Brasil Participativo é implementado.

**Comment by LexTOliver** [comment]
O commit 3c69292dcb8422533860452600a10875bff1a674 apresenta a exportação do modelo para o formato ONNX e a utilização do mesmo em Python. Para Ruby, utiliza-se uma biblioteca similar para carregar o modelo.
