### ISSUE TITLE
Testes e validações da integração do Ruby

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#34]
# Descrição
Realizar testes e validações internas das técnicas de integração.

# Tarefas
- [x] Integrar do produto com uma aplicação Ruby

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovada pelo grupo ou registro na issue com as atividades realizadas.

**Comment by LexTOliver** [comment]
Uma gem foi implementada e publicada através do RubyGems, chamada [proposal-classifier](https://rubygems.org/gems/proposal-classifier). Tem algumas poucas depedências básicas listadas, além de fácil utilizalação. Por fim, só falta detalhar mais a documentação.

**Comment by LexTOliver** [comment]
A implementação da Gem encontra-se em outro repositório ([aqui](https://github.com/chaydson/proposal-classifier)), conforme é requisitado para a úblicação no RubyGems. O cliente já foi consultado quanto a essas questões e só é preciso passar o domínio do repo para a equipe do Brisa.
