### ISSUE TITLE
Otimizações do pré-processamento para o modelo few-shot

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#36]
# Descrição
Otimização do modelo few-shot já implementado

# Tarefas
- [ ] Otimizar o modelo few-shot

# Critérios de Aceitação
- [ ] Branch com as alterações pedidas aprovada pelo grupo

**Comment by LexTOliver** [comment]
O modelo SetFit possui um método de otimização dos hiperparâmetros do modelo. O método realiza testes de treinamento do modelo com várias configurações predefinidas de hiperparâmetros e retorna a configuração que produz a melhor acurácia do modelo.

O [`hyperparameter_search`](https://github.com/huggingface/setfit/blob/main/notebooks/text-classification_hyperparameter-search.ipynb) define duas funções nas quais é definido a inicialização do modelo e as configurações de hiperparâmetros para o teste de treinamento.

**Comment by LexTOliver** [comment]
O [Colab](https://colab.research.google.com/drive/1FE8fQ3oVX1eOw-KP76UvKaI1Waje9pS0?usp=sharing) foi atualizado para realizar o treinamento com os dados do Brasil Participativo (no caso, o `csv` salvo no repo do projeto). O csv necessita conter as limpezas do texto (remoção de tags HTML e links) e também a coluna "id_cats". Para acessar os dados, é possível fazer um upload durante a sessão do Colab ou então pegar diretamente do Google Drive (lembrando de atualizar o caminho do arquivo nos dois casos).

**Comment by LexTOliver** [comment]
Os treinamentos do SetFit realizados nos dados do Brasil Participativo não apresentaram uma boa acurácia. Mesmo com a busca dos melhores hiperparâmetros, o modelo performava uma acurãcia entre 25% a 30%. Mais testes poderiam ser necessários para validar melhor o modelo.

**Comment by LexTOliver** [comment]
Não foi necessário a criação de uma branch, os registros se encontram na issue e o código está disponível pelo link do colab.
