### ISSUE TITLE
Validação do modelo few-shot

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#37]
# Descrição
Verificar se o modelo few-shot teve uma ótima acurácia 

# Tarefas
- [ ] Validar com o cliente se a precisão atende aos requisitos estabelecidos

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovada pelo grupo ou registro na issue com as atividades realizadas.

**Comment by LexTOliver** [comment]
Como visto na issue #36, o modelo não superou nem mesmo o modelo base que temos. Mais estudos seriam necessários para, quem sabe, utilizar um modelo few-shot, todavia não serão realizados dados os prazos de entregas. Desta forma, será mantido o modelo que já possuímos e o modelo few-shot permanece como estudo e tecnologia promissora para adaptação do modelo em outra oportunidade.

**Comment by LexTOliver** [comment]
Não foi necessário a criação da branch e as issues estão com os registros das atividades. Dada a baixa acurácia do modelo, não foi necessário validar o modelo few-shot com o cliente.
