### ISSUE TITLE
Entregar um modelo com 80% de acurácia

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#38]
# Descrição
Entregar o modelo de classificação de propostas do Brasil participativo com 80% de acurácia.

# Tarefas
- [x] Entrega do modelo com 80% de acurácia

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovada pelo grupo

**Comment by jpanacleto2** [comment]
Foram atingidos ate o momento no desenvolvimento do modelo uma acuracia media de 61% disponiveis na 3 versão do modelo, disponivel na pasta `versionamento_modelos` na branch `42-Benchmark-e-versionamento-dos-modelos`

**Comment by Leanddro13** [comment]
Foi realizado o versionamento de dados, sendo concluído na versão 10 do modelo. Infelizmente não alcançamos a nossa meta de 80%. Mas nas versões de versionamento mostram várias técnicas de pre-processamento, algoritmos de treinamento e até técnicas mais avançadas de balanceamento de dados e data augmentation.
