### ISSUE TITLE
Estudar aprendizado não supervisionado e algoritmos de clusterização para texto

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#39]
# Descrição
Brainstorm e estudo geral sobre aprendizado não supervisionado e algoritmos de clusterização; Direcionar estudos de algoritmos para Text Clustering, Document Clustering, ...

# Tarefas
- [ ] Trazer os resultados do estudo

# Critérios de Aceitação
- [ ] Branch com as alterações pedidas aprovada pelo grupo ou registro das atividades realizadas através de comentários na issue.

**Comment by LexTOliver** [comment]
![Scikit-Learn: Choosing the right estimator](https://scikit-learn.org/stable/_static/ml_map.png)

A biblioteca do Scikit-Learn apresenta um mapa para auxiliar na escolha do melhor estimador para o trabalho a ser desenvolvido

**Comment by LexTOliver** [comment]
O algoritmo selecionado para foco, teste e validação foi o LDA.
