### ISSUE TITLE
Documentação da API

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#40]
# Descrição
Documentar a API, para que as próximas pessoas que forem trabalhar no projeto consigam continuar o desenvolvimento.

# Tarefas
- [ ] Documentar API

# Critérios de Aceitação
- [ ] Branch com as alterações pedidas aprovada pelo grupo

**Comment by LexTOliver** [comment]
Movida para issue #3.
