### ISSUE TITLE
Benchmark de algoritmos para Aprendizado Não Supervisionado

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#41]
# Descrição
Implementar tutoriais; Selecionar algoritmos; Realizar benchmark com diferentes modelos em um mesmo dataset

# Tarefas
- [x] Criar um notebook individual mostrando os resultados alcançados
- [x] Escolher o algoritmo com melhor performance e acurácia

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovada pelo grupo ou comentários na issue com as atividades realizadas

**Comment by LexTOliver** [comment]
Segundo o [Scikit-Learn](https://scikit-learn.org/stable/modules/clustering.html#clustering-performance-evaluation):

"Avaliar o desempenho de um algoritmo de agrupamento não é tão trivial quanto contar o número de erros ou a precisão e recuperação de um algoritmo de classificação supervisionado. Em particular, qualquer métrica de avaliação não deve levar em conta os valores absolutos dos rótulos do cluster, mas sim se este agrupamento define separações dos dados semelhantes a algum conjunto de classes reais ou satisfaz alguma suposição de que os membros pertencentes à mesma classe são mais semelhantes do que membros de classes diferentes de acordo com alguma métrica de similaridade."

**Comment by LexTOliver** [comment]
Para avaliação da performance do modelo LDA, a biblioteca Gensim também possui o [CoherenceModel](https://radimrehurek.com/gensim/models/coherencemodel.html) capaz de calcular a pontuação e métricas de coerência dos tópicos definidos pelo modelo treinado.

Dentre as métricas estabelecidas a coerência UMass e CV estão sendo utilizadas. Quanto maior o valor dessas métricas, melhor é a modelagem dos tópicos.

Mais detalhes:
- [Evaluate Topic Models: Latent Dirichlet Allocation (LDA)](https://towardsdatascience.com/evaluate-topic-model-in-python-latent-dirichlet-allocation-lda-7d57484bb5d0)
- [When Coherence Score Is Good or Bad in Topic Modeling?](https://www.baeldung.com/cs/topic-modeling-coherence-score)
