### ISSUE TITLE
Otimizações da classificação de tópicos

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#42]
# Descrição
Realizar correções e otimizações nos modelos selecionados para benchmark

# Tarefas 
- [ ] Testar diferentes métodos de otimizações para aumentar a precisão dos modelos

# Critérios de Aceitação
- [ ] Branch com as alterações pedidas aprovada pelo grupo

**Comment by LexTOliver** [comment]
O treinamento do modelo LDA apresentou bons resultados no treinamento e com o uso do CoherenceModel para avaliação das suas métricas. Ainda /,foram realizados alguns testes modificando os parâmetros do modelo, a quantidade de palavras presentes no dicionário e ajustes no pré-processamento. Desta forma, os parâmetros encontrados no notebook do LDA são os mais adequados até então.
