### ISSUE TITLE
Validação do dataset e dos dados utilizados

### ISSUE THREAD

**Issue by Leanddro13** [ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural#44]
# Descrição
Finalizar o versionamento do dataset com os dados utilizados.

# Tarefas
- [x] Avaliar se os dados não apresentam nenhum padrão falho.
- [x] Avaliar os métodos utilizados no pré-processamento e quão relevantes foram para a precisão dos modelos.
- [x] Realizar modificações, se necessário.
- [x] Garantir a reproducibilidade para criação do dataset

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovada pelo grupo

**Comment by jpanacleto2** [comment]
Foram adicionados ate o momento 3 versões do modelo , disponiveis na branch `42-Benchmark-e-versionamento-dos-modelos`
, com enfoque no pre processamento dos dados.

**Comment by jpanacleto2** [comment]
Os dados utilizados foram validados como eficazes uma vez que são providos pela propria plataforma, alem dos dados simulados tendo sido aprovados pelos integrantes e monitores do projeto
